/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.6.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QStackedWidget>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionMain_page;
    QAction *actionProducts;
    QAction *actionCart;
    QAction *actionPay;
    QAction *actionFeedback;
    QWidget *centralwidget;
    QStackedWidget *stackedWidget;
    QWidget *cart_page;
    QLabel *label_products_21;
    QListWidget *itemsInCartList;
    QPushButton *pushButton;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QLabel *totalPriceText;
    QTableView *tableView_2;
    QLabel *totalPriceInCart;
    QLabel *popcorn_logo;
    QLabel *nachos_logo;
    QWidget *main_page;
    QLabel *label_title;
    QLabel *label_logo;
    QLabel *label_date_time;
    QPushButton *pushButton_2;
    QWidget *products_page;
    QTableView *tableView;
    QLabel *label_products_2;
    QLabel *label_products_3;
    QLabel *label_products_4;
    QLabel *label_products_5;
    QLabel *label_products_6;
    QLabel *label_products_7;
    QFrame *line;
    QFrame *line_2;
    QFrame *line_3;
    QFrame *line_4;
    QFrame *line_5;
    QPushButton *popcorn;
    QPushButton *nachos;
    QPushButton *coke;
    QPushButton *zeroCoke;
    QPushButton *popcornMenu;
    QPushButton *nachosMenu;
    QLabel *label_products_15;
    QLabel *label_products_16;
    QLabel *label_products_17;
    QLabel *label_products_18;
    QLabel *label_products_19;
    QLabel *label_products_20;
    QPushButton *viewCartItems;
    QLabel *label_menu;
    QWidget *pay_page;
    QLabel *label_products_22;
    QLabel *label;
    QLabel *label_2;
    QPushButton *pushButton_6;
    QPushButton *pushButton_5;
    QLabel *label_3;
    QLineEdit *textEditName;
    QLineEdit *textEditNum;
    QLabel *leftPopcorn;
    QLabel *rightPopcorn;
    QPushButton *pushButton_7;
    QLabel *labelPayPrice;
    QLabel *label_15;
    QCheckBox *checkTakeOrder;
    QWidget *feedback_page;
    QLabel *label_products_23;
    QLabel *label_products_24;
    QPushButton *pushBackToMain;
    QLabel *smilePic;
    QLabel *thumbPic;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QFrame *line_6;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QPushButton *pushBackToMain_2;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_4;
    QRadioButton *tasteVeryLow;
    QRadioButton *tasteLow;
    QRadioButton *tasteMedium;
    QRadioButton *tasteHigh;
    QRadioButton *tasteVeryHigh;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout_5;
    QRadioButton *staffVeryLow;
    QRadioButton *staffLow;
    QRadioButton *staffMedium;
    QRadioButton *staffHigh;
    QRadioButton *staffVeryHigh;
    QWidget *layoutWidget2;
    QHBoxLayout *horizontalLayout_6;
    QRadioButton *tempVeryLow;
    QRadioButton *tempLow;
    QRadioButton *tempMedium;
    QRadioButton *tempHigh;
    QRadioButton *tempVeryHigh;
    QWidget *layoutWidget3;
    QHBoxLayout *horizontalLayout_7;
    QRadioButton *decorVeryLow;
    QRadioButton *decorLow;
    QRadioButton *decorMedium;
    QRadioButton *decorHigh;
    QRadioButton *decorVeryHigh;
    QWidget *layoutWidget4;
    QHBoxLayout *horizontalLayout_8;
    QRadioButton *cleanVeryLow;
    QRadioButton *cleanLow;
    QRadioButton *cleanMedium;
    QRadioButton *cleanHigh;
    QRadioButton *cleanVeryHigh;
    QWidget *thanks_page;
    QLabel *label_products_25;
    QLabel *label_products_26;
    QPushButton *pushBackToMain_3;
    QWidget *succes_page;
    QLabel *label_products_28;
    QLabel *label_products_27;
    QPushButton *pushBackToMain_4;
    QStatusBar *statusbar;
    QToolBar *toolBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(845, 600);
        QFont font;
        font.setFamilies({QString::fromUtf8("Script")});
        MainWindow->setFont(font);
        actionMain_page = new QAction(MainWindow);
        actionMain_page->setObjectName("actionMain_page");
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/images/main_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMain_page->setIcon(icon);
        actionProducts = new QAction(MainWindow);
        actionProducts->setObjectName("actionProducts");
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/images/products_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionProducts->setIcon(icon1);
        actionCart = new QAction(MainWindow);
        actionCart->setObjectName("actionCart");
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/images/cart_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCart->setIcon(icon2);
        actionPay = new QAction(MainWindow);
        actionPay->setObjectName("actionPay");
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/images/pay_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPay->setIcon(icon3);
        actionFeedback = new QAction(MainWindow);
        actionFeedback->setObjectName("actionFeedback");
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/images/feedback_icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFeedback->setIcon(icon4);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        stackedWidget = new QStackedWidget(centralwidget);
        stackedWidget->setObjectName("stackedWidget");
        stackedWidget->setGeometry(QRect(20, -10, 751, 611));
        QFont font1;
        font1.setFamilies({QString::fromUtf8("Bookman Old Style")});
        font1.setPointSize(12);
        font1.setItalic(false);
        font1.setUnderline(false);
        stackedWidget->setFont(font1);
        cart_page = new QWidget();
        cart_page->setObjectName("cart_page");
        label_products_21 = new QLabel(cart_page);
        label_products_21->setObjectName("label_products_21");
        label_products_21->setGeometry(QRect(140, 30, 491, 61));
        QFont font2;
        font2.setFamilies({QString::fromUtf8("Candara")});
        font2.setPointSize(28);
        font2.setBold(true);
        font2.setItalic(false);
        font2.setUnderline(false);
        font2.setStrikeOut(false);
        label_products_21->setFont(font2);
        label_products_21->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_21->setAlignment(Qt::AlignCenter);
        itemsInCartList = new QListWidget(cart_page);
        itemsInCartList->setObjectName("itemsInCartList");
        itemsInCartList->setGeometry(QRect(280, 100, 211, 301));
        QFont font3;
        font3.setFamilies({QString::fromUtf8("Times New Roman")});
        font3.setPointSize(12);
        font3.setItalic(false);
        font3.setUnderline(false);
        itemsInCartList->setFont(font3);
        pushButton = new QPushButton(cart_page);
        pushButton->setObjectName("pushButton");
        pushButton->setGeometry(QRect(280, 450, 101, 41));
        pushButton->setFont(font3);
        pushButton_3 = new QPushButton(cart_page);
        pushButton_3->setObjectName("pushButton_3");
        pushButton_3->setGeometry(QRect(390, 450, 101, 41));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(14, 240, 29, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(120, 255, 129, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(67, 247, 79, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(7, 120, 14, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(9, 160, 19, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(134, 247, 142, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 127));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Active, QPalette::Accent, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::Accent, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        QBrush brush10(QColor(7, 120, 14, 127));
        brush10.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush10);
#endif
        QBrush brush11(QColor(72, 255, 84, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::Accent, brush11);
        pushButton_3->setPalette(palette);
        pushButton_3->setFont(font3);
        pushButton_4 = new QPushButton(cart_page);
        pushButton_4->setObjectName("pushButton_4");
        pushButton_4->setGeometry(QRect(350, 500, 81, 31));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush12(QColor(240, 132, 0, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush12);
        QBrush brush13(QColor(255, 188, 105, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush13);
        QBrush brush14(QColor(247, 160, 52, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush14);
        QBrush brush15(QColor(120, 66, 0, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush15);
        QBrush brush16(QColor(160, 88, 0, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush17(QColor(247, 193, 127, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush17);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Active, QPalette::Accent, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush15);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush17);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Inactive, QPalette::Accent, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush16);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush15);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        QBrush brush18(QColor(120, 66, 0, 127));
        brush18.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush18);
#endif
        QBrush brush19(QColor(255, 166, 57, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Disabled, QPalette::Accent, brush19);
        pushButton_4->setPalette(palette1);
        pushButton_4->setFont(font3);
        totalPriceText = new QLabel(cart_page);
        totalPriceText->setObjectName("totalPriceText");
        totalPriceText->setGeometry(QRect(280, 400, 111, 41));
        QFont font4;
        font4.setFamilies({QString::fromUtf8("Times New Roman")});
        font4.setPointSize(12);
        font4.setBold(true);
        font4.setItalic(false);
        font4.setUnderline(false);
        font4.setStrikeOut(false);
        totalPriceText->setFont(font4);
        totalPriceText->setCursor(QCursor(Qt::SizeAllCursor));
        totalPriceText->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tableView_2 = new QTableView(cart_page);
        tableView_2->setObjectName("tableView_2");
        tableView_2->setGeometry(QRect(280, 400, 211, 41));
        totalPriceInCart = new QLabel(cart_page);
        totalPriceInCart->setObjectName("totalPriceInCart");
        totalPriceInCart->setGeometry(QRect(400, 400, 91, 41));
        totalPriceInCart->setFont(font4);
        totalPriceInCart->setCursor(QCursor(Qt::SizeAllCursor));
        totalPriceInCart->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        popcorn_logo = new QLabel(cart_page);
        popcorn_logo->setObjectName("popcorn_logo");
        popcorn_logo->setGeometry(QRect(20, 150, 231, 241));
        QFont font5;
        font5.setFamilies({QString::fromUtf8("Candara")});
        font5.setPointSize(40);
        font5.setBold(true);
        font5.setItalic(false);
        font5.setUnderline(false);
        font5.setStrikeOut(false);
        popcorn_logo->setFont(font5);
        popcorn_logo->setCursor(QCursor(Qt::SizeAllCursor));
        popcorn_logo->setAlignment(Qt::AlignCenter);
        nachos_logo = new QLabel(cart_page);
        nachos_logo->setObjectName("nachos_logo");
        nachos_logo->setGeometry(QRect(490, 160, 231, 241));
        nachos_logo->setFont(font5);
        nachos_logo->setCursor(QCursor(Qt::SizeAllCursor));
        nachos_logo->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(cart_page);
        label_products_21->raise();
        itemsInCartList->raise();
        pushButton->raise();
        pushButton_3->raise();
        pushButton_4->raise();
        tableView_2->raise();
        totalPriceText->raise();
        totalPriceInCart->raise();
        popcorn_logo->raise();
        nachos_logo->raise();
        main_page = new QWidget();
        main_page->setObjectName("main_page");
        label_title = new QLabel(main_page);
        label_title->setObjectName("label_title");
        label_title->setGeometry(QRect(140, 290, 431, 71));
        QFont font6;
        font6.setFamilies({QString::fromUtf8("Candara")});
        font6.setPointSize(45);
        font6.setBold(true);
        font6.setItalic(false);
        font6.setUnderline(false);
        font6.setStrikeOut(false);
        label_title->setFont(font6);
        label_title->setCursor(QCursor(Qt::SizeAllCursor));
        label_title->setAlignment(Qt::AlignCenter);
        label_logo = new QLabel(main_page);
        label_logo->setObjectName("label_logo");
        label_logo->setGeometry(QRect(140, 30, 431, 261));
        label_logo->setFont(font5);
        label_logo->setCursor(QCursor(Qt::SizeAllCursor));
        label_logo->setAlignment(Qt::AlignCenter);
        label_date_time = new QLabel(main_page);
        label_date_time->setObjectName("label_date_time");
        label_date_time->setGeometry(QRect(150, 360, 431, 71));
        QFont font7;
        font7.setFamilies({QString::fromUtf8("Goudy Old Style")});
        font7.setPointSize(35);
        font7.setBold(false);
        font7.setItalic(false);
        font7.setUnderline(false);
        font7.setStrikeOut(false);
        label_date_time->setFont(font7);
        label_date_time->setCursor(QCursor(Qt::SizeAllCursor));
        label_date_time->setAlignment(Qt::AlignCenter);
        pushButton_2 = new QPushButton(main_page);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(280, 440, 181, 71));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush20(QColor(240, 0, 0, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush20);
        QBrush brush21(QColor(255, 105, 105, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush21);
        QBrush brush22(QColor(247, 52, 52, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush22);
        QBrush brush23(QColor(120, 0, 0, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush23);
        QBrush brush24(QColor(160, 0, 0, 255));
        brush24.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush25(QColor(247, 127, 127, 255));
        brush25.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush25);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Active, QPalette::Accent, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush21);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush22);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush23);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush25);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Inactive, QPalette::Accent, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush21);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush22);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush24);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
        QBrush brush26(QColor(120, 0, 0, 127));
        brush26.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush26);
#endif
        QBrush brush27(QColor(255, 57, 57, 255));
        brush27.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::Accent, brush27);
        pushButton_2->setPalette(palette2);
        QFont font8;
        font8.setFamilies({QString::fromUtf8("Comic Sans MS")});
        font8.setPointSize(20);
        font8.setItalic(false);
        font8.setUnderline(false);
        pushButton_2->setFont(font8);
        stackedWidget->addWidget(main_page);
        products_page = new QWidget();
        products_page->setObjectName("products_page");
        tableView = new QTableView(products_page);
        tableView->setObjectName("tableView");
        tableView->setGeometry(QRect(60, 70, 631, 421));
        label_products_2 = new QLabel(products_page);
        label_products_2->setObjectName("label_products_2");
        label_products_2->setGeometry(QRect(80, 70, 171, 61));
        QFont font9;
        font9.setFamilies({QString::fromUtf8("Candara")});
        font9.setPointSize(20);
        font9.setBold(true);
        font9.setItalic(false);
        font9.setUnderline(false);
        font9.setStrikeOut(false);
        label_products_2->setFont(font9);
        label_products_2->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_3 = new QLabel(products_page);
        label_products_3->setObjectName("label_products_3");
        label_products_3->setGeometry(QRect(80, 130, 171, 61));
        label_products_3->setFont(font9);
        label_products_3->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_4 = new QLabel(products_page);
        label_products_4->setObjectName("label_products_4");
        label_products_4->setGeometry(QRect(80, 190, 121, 61));
        label_products_4->setFont(font9);
        label_products_4->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_5 = new QLabel(products_page);
        label_products_5->setObjectName("label_products_5");
        label_products_5->setGeometry(QRect(80, 260, 171, 61));
        label_products_5->setFont(font9);
        label_products_5->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_6 = new QLabel(products_page);
        label_products_6->setObjectName("label_products_6");
        label_products_6->setGeometry(QRect(80, 300, 381, 121));
        label_products_6->setFont(font9);
        label_products_6->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_7 = new QLabel(products_page);
        label_products_7->setObjectName("label_products_7");
        label_products_7->setGeometry(QRect(80, 400, 401, 91));
        label_products_7->setFont(font9);
        label_products_7->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        line = new QFrame(products_page);
        line->setObjectName("line");
        line->setGeometry(QRect(80, 120, 581, 20));
        line->setFrameShape(QFrame::HLine);
        line->setFrameShadow(QFrame::Sunken);
        line_2 = new QFrame(products_page);
        line_2->setObjectName("line_2");
        line_2->setGeometry(QRect(80, 180, 581, 20));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);
        line_3 = new QFrame(products_page);
        line_3->setObjectName("line_3");
        line_3->setGeometry(QRect(80, 250, 581, 20));
        line_3->setFrameShape(QFrame::HLine);
        line_3->setFrameShadow(QFrame::Sunken);
        line_4 = new QFrame(products_page);
        line_4->setObjectName("line_4");
        line_4->setGeometry(QRect(80, 310, 581, 20));
        line_4->setFrameShape(QFrame::HLine);
        line_4->setFrameShadow(QFrame::Sunken);
        line_5 = new QFrame(products_page);
        line_5->setObjectName("line_5");
        line_5->setGeometry(QRect(80, 400, 581, 20));
        line_5->setFrameShape(QFrame::HLine);
        line_5->setFrameShadow(QFrame::Sunken);
        popcorn = new QPushButton(products_page);
        popcorn->setObjectName("popcorn");
        popcorn->setGeometry(QRect(590, 80, 71, 41));
        popcorn->setFont(font3);
        nachos = new QPushButton(products_page);
        nachos->setObjectName("nachos");
        nachos->setGeometry(QRect(590, 140, 71, 41));
        nachos->setFont(font3);
        coke = new QPushButton(products_page);
        coke->setObjectName("coke");
        coke->setGeometry(QRect(590, 200, 71, 41));
        coke->setFont(font3);
        zeroCoke = new QPushButton(products_page);
        zeroCoke->setObjectName("zeroCoke");
        zeroCoke->setGeometry(QRect(590, 270, 71, 41));
        zeroCoke->setFont(font3);
        popcornMenu = new QPushButton(products_page);
        popcornMenu->setObjectName("popcornMenu");
        popcornMenu->setGeometry(QRect(590, 340, 71, 41));
        popcornMenu->setFont(font3);
        nachosMenu = new QPushButton(products_page);
        nachosMenu->setObjectName("nachosMenu");
        nachosMenu->setGeometry(QRect(590, 430, 71, 41));
        nachosMenu->setFont(font3);
        label_products_15 = new QLabel(products_page);
        label_products_15->setObjectName("label_products_15");
        label_products_15->setGeometry(QRect(500, 70, 81, 61));
        QFont font10;
        font10.setFamilies({QString::fromUtf8("Times New Roman")});
        font10.setPointSize(18);
        font10.setBold(true);
        font10.setItalic(true);
        font10.setUnderline(false);
        font10.setStrikeOut(false);
        label_products_15->setFont(font10);
        label_products_15->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_15->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_16 = new QLabel(products_page);
        label_products_16->setObjectName("label_products_16");
        label_products_16->setGeometry(QRect(500, 130, 81, 61));
        label_products_16->setFont(font10);
        label_products_16->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_16->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_17 = new QLabel(products_page);
        label_products_17->setObjectName("label_products_17");
        label_products_17->setGeometry(QRect(500, 190, 81, 61));
        label_products_17->setFont(font10);
        label_products_17->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_17->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_18 = new QLabel(products_page);
        label_products_18->setObjectName("label_products_18");
        label_products_18->setGeometry(QRect(500, 260, 81, 61));
        label_products_18->setFont(font10);
        label_products_18->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_18->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_19 = new QLabel(products_page);
        label_products_19->setObjectName("label_products_19");
        label_products_19->setGeometry(QRect(500, 330, 81, 61));
        label_products_19->setFont(font10);
        label_products_19->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_19->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_products_20 = new QLabel(products_page);
        label_products_20->setObjectName("label_products_20");
        label_products_20->setGeometry(QRect(500, 420, 81, 61));
        label_products_20->setFont(font10);
        label_products_20->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_20->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        viewCartItems = new QPushButton(products_page);
        viewCartItems->setObjectName("viewCartItems");
        viewCartItems->setGeometry(QRect(300, 500, 141, 51));
        QFont font11;
        font11.setFamilies({QString::fromUtf8("Times New Roman")});
        font11.setPointSize(15);
        font11.setItalic(false);
        font11.setUnderline(false);
        viewCartItems->setFont(font11);
        label_menu = new QLabel(products_page);
        label_menu->setObjectName("label_menu");
        label_menu->setGeometry(QRect(250, 20, 231, 71));
        QFont font12;
        font12.setFamilies({QString::fromUtf8("Cambria")});
        font12.setPointSize(20);
        font12.setBold(true);
        font12.setItalic(false);
        font12.setUnderline(false);
        label_menu->setFont(font12);
        label_menu->setAlignment(Qt::AlignCenter);
        stackedWidget->addWidget(products_page);
        pay_page = new QWidget();
        pay_page->setObjectName("pay_page");
        label_products_22 = new QLabel(pay_page);
        label_products_22->setObjectName("label_products_22");
        label_products_22->setGeometry(QRect(120, 30, 491, 61));
        label_products_22->setFont(font2);
        label_products_22->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_22->setAlignment(Qt::AlignCenter);
        label = new QLabel(pay_page);
        label->setObjectName("label");
        label->setGeometry(QRect(250, 120, 231, 31));
        QFont font13;
        font13.setFamilies({QString::fromUtf8("Cambria")});
        font13.setPointSize(12);
        font13.setItalic(false);
        font13.setUnderline(false);
        label->setFont(font13);
        label_2 = new QLabel(pay_page);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(210, 230, 301, 31));
        label_2->setFont(font13);
        label_2->setAlignment(Qt::AlignCenter);
        pushButton_6 = new QPushButton(pay_page);
        pushButton_6->setObjectName("pushButton_6");
        pushButton_6->setGeometry(QRect(250, 510, 101, 31));
        pushButton_6->setFont(font3);
        pushButton_5 = new QPushButton(pay_page);
        pushButton_5->setObjectName("pushButton_5");
        pushButton_5->setGeometry(QRect(250, 450, 221, 41));
        QFont font14;
        font14.setFamilies({QString::fromUtf8("Times New Roman")});
        font14.setPointSize(14);
        font14.setItalic(false);
        font14.setUnderline(false);
        pushButton_5->setFont(font14);
        label_3 = new QLabel(pay_page);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(290, 400, 111, 31));
        QFont font15;
        font15.setFamilies({QString::fromUtf8("Cambria")});
        font15.setPointSize(12);
        font15.setBold(true);
        font15.setItalic(false);
        font15.setUnderline(false);
        label_3->setFont(font15);
        textEditName = new QLineEdit(pay_page);
        textEditName->setObjectName("textEditName");
        textEditName->setGeometry(QRect(240, 160, 241, 31));
        textEditName->setFont(font13);
        textEditNum = new QLineEdit(pay_page);
        textEditNum->setObjectName("textEditNum");
        textEditNum->setGeometry(QRect(240, 270, 241, 31));
        textEditNum->setFont(font13);
        leftPopcorn = new QLabel(pay_page);
        leftPopcorn->setObjectName("leftPopcorn");
        leftPopcorn->setGeometry(QRect(20, 140, 171, 301));
        leftPopcorn->setAlignment(Qt::AlignCenter);
        rightPopcorn = new QLabel(pay_page);
        rightPopcorn->setObjectName("rightPopcorn");
        rightPopcorn->setGeometry(QRect(540, 140, 171, 301));
        rightPopcorn->setAlignment(Qt::AlignCenter);
        pushButton_7 = new QPushButton(pay_page);
        pushButton_7->setObjectName("pushButton_7");
        pushButton_7->setGeometry(QRect(370, 510, 101, 31));
        pushButton_7->setFont(font3);
        labelPayPrice = new QLabel(pay_page);
        labelPayPrice->setObjectName("labelPayPrice");
        labelPayPrice->setGeometry(QRect(380, 400, 61, 31));
        labelPayPrice->setFont(font15);
        labelPayPrice->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_15 = new QLabel(pay_page);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(210, 310, 301, 31));
        label_15->setFont(font13);
        label_15->setAlignment(Qt::AlignCenter);
        checkTakeOrder = new QCheckBox(pay_page);
        checkTakeOrder->setObjectName("checkTakeOrder");
        checkTakeOrder->setGeometry(QRect(270, 350, 221, 26));
        stackedWidget->addWidget(pay_page);
        feedback_page = new QWidget();
        feedback_page->setObjectName("feedback_page");
        label_products_23 = new QLabel(feedback_page);
        label_products_23->setObjectName("label_products_23");
        label_products_23->setGeometry(QRect(110, 30, 491, 61));
        label_products_23->setFont(font2);
        label_products_23->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_23->setAlignment(Qt::AlignCenter);
        label_products_24 = new QLabel(feedback_page);
        label_products_24->setObjectName("label_products_24");
        label_products_24->setGeometry(QRect(120, 80, 491, 61));
        QFont font16;
        font16.setFamilies({QString::fromUtf8("Candara")});
        font16.setPointSize(12);
        font16.setBold(false);
        font16.setItalic(false);
        font16.setUnderline(false);
        font16.setStrikeOut(false);
        label_products_24->setFont(font16);
        label_products_24->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_24->setAlignment(Qt::AlignCenter);
        pushBackToMain = new QPushButton(feedback_page);
        pushBackToMain->setObjectName("pushBackToMain");
        pushBackToMain->setGeometry(QRect(250, 440, 101, 41));
        QFont font17;
        font17.setFamilies({QString::fromUtf8("Cambria")});
        font17.setPointSize(13);
        font17.setItalic(false);
        font17.setUnderline(false);
        pushBackToMain->setFont(font17);
        smilePic = new QLabel(feedback_page);
        smilePic->setObjectName("smilePic");
        smilePic->setGeometry(QRect(530, 40, 101, 81));
        QFont font18;
        font18.setFamilies({QString::fromUtf8("Candara")});
        font18.setPointSize(15);
        font18.setBold(true);
        font18.setItalic(false);
        font18.setUnderline(false);
        font18.setStrikeOut(false);
        smilePic->setFont(font18);
        smilePic->setCursor(QCursor(Qt::SizeAllCursor));
        smilePic->setAlignment(Qt::AlignCenter);
        thumbPic = new QLabel(feedback_page);
        thumbPic->setObjectName("thumbPic");
        thumbPic->setGeometry(QRect(100, 40, 101, 81));
        thumbPic->setFont(font18);
        thumbPic->setCursor(QCursor(Qt::SizeAllCursor));
        thumbPic->setAlignment(Qt::AlignCenter);
        label_4 = new QLabel(feedback_page);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(110, 380, 111, 21));
        label_4->setFont(font3);
        label_5 = new QLabel(feedback_page);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(110, 340, 111, 20));
        label_5->setFont(font3);
        label_6 = new QLabel(feedback_page);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(110, 300, 151, 21));
        label_6->setFont(font3);
        label_7 = new QLabel(feedback_page);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(110, 260, 111, 21));
        label_7->setFont(font3);
        label_8 = new QLabel(feedback_page);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(110, 220, 111, 21));
        label_8->setFont(font3);
        label_9 = new QLabel(feedback_page);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(110, 170, 161, 21));
        QFont font19;
        font19.setFamilies({QString::fromUtf8("Times New Roman")});
        font19.setPointSize(12);
        font19.setBold(true);
        font19.setItalic(false);
        font19.setUnderline(false);
        label_9->setFont(font19);
        label_9->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        line_6 = new QFrame(feedback_page);
        line_6->setObjectName("line_6");
        line_6->setGeometry(QRect(270, 190, 381, 20));
        line_6->setFrameShape(QFrame::HLine);
        line_6->setFrameShadow(QFrame::Sunken);
        label_10 = new QLabel(feedback_page);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(370, 160, 41, 31));
        QFont font20;
        font20.setFamilies({QString::fromUtf8("Times New Roman")});
        font20.setPointSize(11);
        font20.setItalic(false);
        font20.setUnderline(false);
        label_10->setFont(font20);
        label_10->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_11 = new QLabel(feedback_page);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(440, 160, 71, 31));
        label_11->setFont(font20);
        label_11->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_12 = new QLabel(feedback_page);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(280, 160, 71, 31));
        label_12->setFont(font20);
        label_12->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_13 = new QLabel(feedback_page);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(530, 160, 41, 31));
        label_13->setFont(font20);
        label_13->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        label_14 = new QLabel(feedback_page);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(580, 160, 71, 31));
        label_14->setFont(font20);
        label_14->setAlignment(Qt::AlignBottom|Qt::AlignLeading|Qt::AlignLeft);
        pushBackToMain_2 = new QPushButton(feedback_page);
        pushBackToMain_2->setObjectName("pushBackToMain_2");
        pushBackToMain_2->setGeometry(QRect(390, 440, 101, 41));
        pushBackToMain_2->setFont(font17);
        layoutWidget = new QWidget(feedback_page);
        layoutWidget->setObjectName("layoutWidget");
        layoutWidget->setGeometry(QRect(301, 221, 381, 20));
        horizontalLayout_4 = new QHBoxLayout(layoutWidget);
        horizontalLayout_4->setObjectName("horizontalLayout_4");
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        tasteVeryLow = new QRadioButton(layoutWidget);
        tasteVeryLow->setObjectName("tasteVeryLow");

        horizontalLayout_4->addWidget(tasteVeryLow);

        tasteLow = new QRadioButton(layoutWidget);
        tasteLow->setObjectName("tasteLow");

        horizontalLayout_4->addWidget(tasteLow);

        tasteMedium = new QRadioButton(layoutWidget);
        tasteMedium->setObjectName("tasteMedium");

        horizontalLayout_4->addWidget(tasteMedium);

        tasteHigh = new QRadioButton(layoutWidget);
        tasteHigh->setObjectName("tasteHigh");

        horizontalLayout_4->addWidget(tasteHigh);

        tasteVeryHigh = new QRadioButton(layoutWidget);
        tasteVeryHigh->setObjectName("tasteVeryHigh");

        horizontalLayout_4->addWidget(tasteVeryHigh);

        tasteLow->raise();
        tasteMedium->raise();
        tasteHigh->raise();
        tasteVeryHigh->raise();
        tasteVeryLow->raise();
        layoutWidget1 = new QWidget(feedback_page);
        layoutWidget1->setObjectName("layoutWidget1");
        layoutWidget1->setGeometry(QRect(301, 261, 381, 20));
        horizontalLayout_5 = new QHBoxLayout(layoutWidget1);
        horizontalLayout_5->setObjectName("horizontalLayout_5");
        horizontalLayout_5->setContentsMargins(0, 0, 0, 0);
        staffVeryLow = new QRadioButton(layoutWidget1);
        staffVeryLow->setObjectName("staffVeryLow");

        horizontalLayout_5->addWidget(staffVeryLow);

        staffLow = new QRadioButton(layoutWidget1);
        staffLow->setObjectName("staffLow");

        horizontalLayout_5->addWidget(staffLow);

        staffMedium = new QRadioButton(layoutWidget1);
        staffMedium->setObjectName("staffMedium");

        horizontalLayout_5->addWidget(staffMedium);

        staffHigh = new QRadioButton(layoutWidget1);
        staffHigh->setObjectName("staffHigh");

        horizontalLayout_5->addWidget(staffHigh);

        staffVeryHigh = new QRadioButton(layoutWidget1);
        staffVeryHigh->setObjectName("staffVeryHigh");

        horizontalLayout_5->addWidget(staffVeryHigh);

        layoutWidget2 = new QWidget(feedback_page);
        layoutWidget2->setObjectName("layoutWidget2");
        layoutWidget2->setGeometry(QRect(301, 301, 381, 20));
        horizontalLayout_6 = new QHBoxLayout(layoutWidget2);
        horizontalLayout_6->setObjectName("horizontalLayout_6");
        horizontalLayout_6->setContentsMargins(0, 0, 0, 0);
        tempVeryLow = new QRadioButton(layoutWidget2);
        tempVeryLow->setObjectName("tempVeryLow");

        horizontalLayout_6->addWidget(tempVeryLow);

        tempLow = new QRadioButton(layoutWidget2);
        tempLow->setObjectName("tempLow");

        horizontalLayout_6->addWidget(tempLow);

        tempMedium = new QRadioButton(layoutWidget2);
        tempMedium->setObjectName("tempMedium");

        horizontalLayout_6->addWidget(tempMedium);

        tempHigh = new QRadioButton(layoutWidget2);
        tempHigh->setObjectName("tempHigh");

        horizontalLayout_6->addWidget(tempHigh);

        tempVeryHigh = new QRadioButton(layoutWidget2);
        tempVeryHigh->setObjectName("tempVeryHigh");

        horizontalLayout_6->addWidget(tempVeryHigh);

        layoutWidget3 = new QWidget(feedback_page);
        layoutWidget3->setObjectName("layoutWidget3");
        layoutWidget3->setGeometry(QRect(301, 341, 381, 20));
        horizontalLayout_7 = new QHBoxLayout(layoutWidget3);
        horizontalLayout_7->setObjectName("horizontalLayout_7");
        horizontalLayout_7->setContentsMargins(0, 0, 0, 0);
        decorVeryLow = new QRadioButton(layoutWidget3);
        decorVeryLow->setObjectName("decorVeryLow");

        horizontalLayout_7->addWidget(decorVeryLow);

        decorLow = new QRadioButton(layoutWidget3);
        decorLow->setObjectName("decorLow");

        horizontalLayout_7->addWidget(decorLow);

        decorMedium = new QRadioButton(layoutWidget3);
        decorMedium->setObjectName("decorMedium");

        horizontalLayout_7->addWidget(decorMedium);

        decorHigh = new QRadioButton(layoutWidget3);
        decorHigh->setObjectName("decorHigh");

        horizontalLayout_7->addWidget(decorHigh);

        decorVeryHigh = new QRadioButton(layoutWidget3);
        decorVeryHigh->setObjectName("decorVeryHigh");

        horizontalLayout_7->addWidget(decorVeryHigh);

        layoutWidget4 = new QWidget(feedback_page);
        layoutWidget4->setObjectName("layoutWidget4");
        layoutWidget4->setGeometry(QRect(301, 381, 381, 20));
        horizontalLayout_8 = new QHBoxLayout(layoutWidget4);
        horizontalLayout_8->setObjectName("horizontalLayout_8");
        horizontalLayout_8->setContentsMargins(0, 0, 0, 0);
        cleanVeryLow = new QRadioButton(layoutWidget4);
        cleanVeryLow->setObjectName("cleanVeryLow");

        horizontalLayout_8->addWidget(cleanVeryLow);

        cleanLow = new QRadioButton(layoutWidget4);
        cleanLow->setObjectName("cleanLow");

        horizontalLayout_8->addWidget(cleanLow);

        cleanMedium = new QRadioButton(layoutWidget4);
        cleanMedium->setObjectName("cleanMedium");

        horizontalLayout_8->addWidget(cleanMedium);

        cleanHigh = new QRadioButton(layoutWidget4);
        cleanHigh->setObjectName("cleanHigh");

        horizontalLayout_8->addWidget(cleanHigh);

        cleanVeryHigh = new QRadioButton(layoutWidget4);
        cleanVeryHigh->setObjectName("cleanVeryHigh");

        horizontalLayout_8->addWidget(cleanVeryHigh);

        stackedWidget->addWidget(feedback_page);
        layoutWidget1->raise();
        layoutWidget1->raise();
        layoutWidget1->raise();
        layoutWidget1->raise();
        layoutWidget1->raise();
        label_products_23->raise();
        pushBackToMain->raise();
        label_products_24->raise();
        smilePic->raise();
        thumbPic->raise();
        label_4->raise();
        label_5->raise();
        label_6->raise();
        label_7->raise();
        label_8->raise();
        label_9->raise();
        line_6->raise();
        label_10->raise();
        label_11->raise();
        label_12->raise();
        label_13->raise();
        label_14->raise();
        pushBackToMain_2->raise();
        thanks_page = new QWidget();
        thanks_page->setObjectName("thanks_page");
        label_products_25 = new QLabel(thanks_page);
        label_products_25->setObjectName("label_products_25");
        label_products_25->setGeometry(QRect(220, 190, 271, 61));
        label_products_25->setFont(font2);
        label_products_25->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_25->setAlignment(Qt::AlignCenter);
        label_products_26 = new QLabel(thanks_page);
        label_products_26->setObjectName("label_products_26");
        label_products_26->setGeometry(QRect(110, 240, 491, 51));
        label_products_26->setFont(font16);
        label_products_26->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_26->setAlignment(Qt::AlignCenter);
        pushBackToMain_3 = new QPushButton(thanks_page);
        pushBackToMain_3->setObjectName("pushBackToMain_3");
        pushBackToMain_3->setGeometry(QRect(310, 300, 101, 41));
        pushBackToMain_3->setFont(font17);
        stackedWidget->addWidget(thanks_page);
        succes_page = new QWidget();
        succes_page->setObjectName("succes_page");
        label_products_28 = new QLabel(succes_page);
        label_products_28->setObjectName("label_products_28");
        label_products_28->setGeometry(QRect(200, 190, 351, 61));
        label_products_28->setFont(font2);
        label_products_28->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_28->setAlignment(Qt::AlignCenter);
        label_products_27 = new QLabel(succes_page);
        label_products_27->setObjectName("label_products_27");
        label_products_27->setGeometry(QRect(130, 250, 491, 51));
        label_products_27->setFont(font16);
        label_products_27->setCursor(QCursor(Qt::SizeAllCursor));
        label_products_27->setAlignment(Qt::AlignCenter);
        pushBackToMain_4 = new QPushButton(succes_page);
        pushBackToMain_4->setObjectName("pushBackToMain_4");
        pushBackToMain_4->setGeometry(QRect(330, 310, 101, 41));
        pushBackToMain_4->setFont(font17);
        stackedWidget->addWidget(succes_page);
        MainWindow->setCentralWidget(centralwidget);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);
        toolBar = new QToolBar(MainWindow);
        toolBar->setObjectName("toolBar");
        QFont font21;
        font21.setFamilies({QString::fromUtf8("Script")});
        font21.setPointSize(7);
        font21.setItalic(false);
        toolBar->setFont(font21);
        toolBar->setMovable(false);
        toolBar->setAllowedAreas(Qt::AllToolBarAreas);
        toolBar->setIconSize(QSize(45, 45));
        MainWindow->addToolBar(Qt::LeftToolBarArea, toolBar);

        toolBar->addAction(actionMain_page);
        toolBar->addSeparator();
        toolBar->addAction(actionProducts);
        toolBar->addAction(actionCart);
        toolBar->addAction(actionPay);
        toolBar->addSeparator();
        toolBar->addAction(actionFeedback);

        retranslateUi(MainWindow);

        stackedWidget->setCurrentIndex(4);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        actionMain_page->setText(QCoreApplication::translate("MainWindow", "Main page", nullptr));
        actionProducts->setText(QCoreApplication::translate("MainWindow", "Products", nullptr));
        actionCart->setText(QCoreApplication::translate("MainWindow", "Cart", nullptr));
        actionPay->setText(QCoreApplication::translate("MainWindow", "Pay", nullptr));
        actionFeedback->setText(QCoreApplication::translate("MainWindow", "Feedback", nullptr));
        label_products_21->setText(QCoreApplication::translate("MainWindow", "My Cart", nullptr));
        pushButton->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        pushButton_3->setText(QCoreApplication::translate("MainWindow", "Pay", nullptr));
        pushButton_4->setText(QCoreApplication::translate("MainWindow", "Delete", nullptr));
        totalPriceText->setText(QCoreApplication::translate("MainWindow", " Total price:", nullptr));
        totalPriceInCart->setText(QCoreApplication::translate("MainWindow", "$0.00 ", nullptr));
        popcorn_logo->setText(QCoreApplication::translate("MainWindow", "LOGO", nullptr));
        nachos_logo->setText(QCoreApplication::translate("MainWindow", "LOGO", nullptr));
        label_title->setText(QCoreApplication::translate("MainWindow", "Snack Surf", nullptr));
        label_logo->setText(QCoreApplication::translate("MainWindow", "LOGO", nullptr));
        label_date_time->setText(QCoreApplication::translate("MainWindow", "19:21:10", nullptr));
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Let's start!", nullptr));
        label_products_2->setText(QCoreApplication::translate("MainWindow", "Popcorn", nullptr));
        label_products_3->setText(QCoreApplication::translate("MainWindow", "Nachos", nullptr));
        label_products_4->setText(QCoreApplication::translate("MainWindow", "Coke", nullptr));
        label_products_5->setText(QCoreApplication::translate("MainWindow", "Zero Coke", nullptr));
        label_products_6->setText(QCoreApplication::translate("MainWindow", "Popcorn menu \n"
"(popcorn + beverage)", nullptr));
        label_products_7->setText(QCoreApplication::translate("MainWindow", "Nachos menu \n"
"(nachos + beverage)", nullptr));
        popcorn->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        nachos->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        coke->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        zeroCoke->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        popcornMenu->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        nachosMenu->setText(QCoreApplication::translate("MainWindow", "Add", nullptr));
        label_products_15->setText(QCoreApplication::translate("MainWindow", "$4.5", nullptr));
        label_products_16->setText(QCoreApplication::translate("MainWindow", "$4.5", nullptr));
        label_products_17->setText(QCoreApplication::translate("MainWindow", "$1.6", nullptr));
        label_products_18->setText(QCoreApplication::translate("MainWindow", "$1.6", nullptr));
        label_products_19->setText(QCoreApplication::translate("MainWindow", "$5.8", nullptr));
        label_products_20->setText(QCoreApplication::translate("MainWindow", "$5.8", nullptr));
        viewCartItems->setText(QCoreApplication::translate("MainWindow", "View Cart", nullptr));
        label_menu->setText(QCoreApplication::translate("MainWindow", "MENU LOGO", nullptr));
        label_products_22->setText(QCoreApplication::translate("MainWindow", "Order & Payment", nullptr));
        label->setText(QCoreApplication::translate("MainWindow", "Your Nickname (optional)", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindow", "Pick a number (on your left)", nullptr));
        pushButton_6->setText(QCoreApplication::translate("MainWindow", "Back", nullptr));
        pushButton_5->setText(QCoreApplication::translate("MainWindow", "Pay at the cash register", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindow", "Total price: ", nullptr));
        leftPopcorn->setText(QCoreApplication::translate("MainWindow", "leftPopcorn", nullptr));
        rightPopcorn->setText(QCoreApplication::translate("MainWindow", "rightPopcorn", nullptr));
        pushButton_7->setText(QCoreApplication::translate("MainWindow", "Cancel Order", nullptr));
        labelPayPrice->setText(QCoreApplication::translate("MainWindow", "$0.00", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindow", "OR", nullptr));
        checkTakeOrder->setText(QCoreApplication::translate("MainWindow", "I will take the order.", nullptr));
        label_products_23->setText(QCoreApplication::translate("MainWindow", "Rate us!", nullptr));
        label_products_24->setText(QCoreApplication::translate("MainWindow", "One minute for you, lot of help for us!", nullptr));
        pushBackToMain->setText(QCoreApplication::translate("MainWindow", "Not now", nullptr));
        smilePic->setText(QCoreApplication::translate("MainWindow", "SMILE", nullptr));
        thumbPic->setText(QCoreApplication::translate("MainWindow", "UP", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindow", "Cleaniness", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindow", "Decoration", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindow", "Food temperature", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindow", "Staff", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindow", "Taste", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindow", "Satisfaction level:", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindow", "Low", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindow", "Medium", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindow", "Very low", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindow", "High", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindow", "Very high", nullptr));
        pushBackToMain_2->setText(QCoreApplication::translate("MainWindow", "Send", nullptr));
        tasteVeryLow->setText(QString());
        tasteLow->setText(QString());
        tasteMedium->setText(QString());
        tasteHigh->setText(QString());
        tasteVeryHigh->setText(QString());
        staffVeryLow->setText(QString());
        staffLow->setText(QString());
        staffMedium->setText(QString());
        staffHigh->setText(QString());
        staffVeryHigh->setText(QString());
        tempVeryLow->setText(QString());
        tempLow->setText(QString());
        tempMedium->setText(QString());
        tempHigh->setText(QString());
        tempVeryHigh->setText(QString());
        decorVeryLow->setText(QString());
        decorLow->setText(QString());
        decorMedium->setText(QString());
        decorHigh->setText(QString());
        decorVeryHigh->setText(QString());
        cleanVeryLow->setText(QString());
        cleanLow->setText(QString());
        cleanMedium->setText(QString());
        cleanHigh->setText(QString());
        cleanVeryHigh->setText(QString());
        label_products_25->setText(QCoreApplication::translate("MainWindow", "Thank you!", nullptr));
        label_products_26->setText(QCoreApplication::translate("MainWindow", "We appreciate your time!", nullptr));
        pushBackToMain_3->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        label_products_28->setText(QCoreApplication::translate("MainWindow", "Succesful order!", nullptr));
        label_products_27->setText(QCoreApplication::translate("MainWindow", "Watch your number on the screen.\n"
"You can pay at the cash register.", nullptr));
        pushBackToMain_4->setText(QCoreApplication::translate("MainWindow", "OK", nullptr));
        toolBar->setWindowTitle(QCoreApplication::translate("MainWindow", "toolBar", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
